openapi: 3.0.0
info:
  title: eBird API Integration
  version: 1.0.0
servers:
  - url: 'https://api.ebird.org/v2'
paths:
  /data/obs/{regionCode}/historic/{y}/{m}/{d}:
    get:
      summary: Historic Observations on a Date
      operationId: getHistoricObservations
      parameters:
        - name: regionCode
          in: path
          required: true
          schema:
            type: string
            pattern: ^example-[0-9a-z]+$
            maxLength: 32
        - name: y
          in: path
          required: true
          schema:
            type: string
            pattern: ^example-[0-9a-z]+$
            maxLength: 32
        - name: m
          in: path
          required: true
          schema:
            type: string
            pattern: ^example-[0-9a-z]+$
            maxLength: 32
        - name: d
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful response
        '401':
          description: Unauthorized
        '403':
          description: Unauthorized
        '404':
          description: Unauthorized
        '429':
          description: Unauthorized
        default:
          description: Unauthorized
  /product/top100/{regionCode}/{y}/{m}/{d}:
    get:
      summary: Top 100 Contributors on a Given Date
      operationId: getTopContributors
      parameters:
        - name: regionCode
          in: path
          required: true
          schema:
            type: string
        - name: y
          in: path
          required: true
          schema:
            type: string
        - name: m
          in: path
          required: true
          schema:
            type: string
        - name: d
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful response
  /data/obs/geo/recent/{speciesCode}:
    get:
      summary: Recent Nearby Observations of a Species
      operationId: getRecentNearbyObservations
      parameters:
        - name: speciesCode
          in: path
          required: true
          schema:
            type: string
        - name: lat
          in: query
          required: true
          schema:
            type: number
            format: double
        - name: lng
          in: query
          required: true
          schema:
            type: number
            format: double
      responses:
        '200':
          description: Successful response
  /data/nearest/geo/recent/{speciesCode}:
    get:
      summary: Nearest Observations of a Species
      operationId: getNearestObservations
      parameters:
        - name: speciesCode
          in: path
          required: true
          schema:
            type: string
        - name: lat
          in: query
          required: true
          schema:
            type: number
            format: double
        - name: lng
          in: query
          required: true
          schema:
            type: number
            format: double
      responses:
        '200':
          description: Successful response
  /data/obs/geo/recent{speciesCode}:
    get:
      summary: Get the list of recent observations of birds seen at locations
      parameters:
      - name: lat
        in: query
        required: true
        description: Latitude to 2 decimal places
        schema:
          type: number
      - name: lng
        in: query
        required: true
        description: Longitude to 2 decimal places
        schema:
          type: number
      - name: back
        in: query
        description: The number of days back to fetch observations.
        schema:
          type: integer
          default: 14
          minimum: 1
          maximum: 30
      - name: cat
        in: query
        description: Only fetch observations from these taxonomic categories.
        schema:
          type: string
          default: all
      - name: dist
        in: query
        description: The search radius from the given position, in kilometers.
        schema:
          type: integer
          default: 25
          minimum: 0
          maximum: 50
      - name: hotspot
        in: query
        description: Only fetch observations from hotspots.
        schema:
          type: boolean
          default: false
      - name: includeProvisional
        in: query
        description: Include observations which have not yet been reviewed.
        schema:
          type: boolean
          default: false
      - name: maxResults
        in: query
        description: Only fetch this number of observations.
        schema:
          type: integer
          default: all
          minimum: 1
          maximum: 10000
      - name: sort
        in: query
        description: Sort observations by taxonomy or by date, most recent first.
        schema:
          type: string
          default: date
      - name: sppLocale
        in: query
        description: Use this language for species common names.
        schema:
          type: string
          default: en
      responses:
        '200':
          description: List of recent observations
          content:
            application/json:
              schema:
                type: array
                items:
                  "$ref": "#/components/schemas/Observation"
  /data/obs/{regionCode}/recent:
    get:
      operationId: getRecentObservations
      summary: Recent observations in a region
      parameters:
      - name: regionCode
        in: path
        required: true
        description: The country, subnational1, subnational2 or location code.
        schema:
          type: string
      - name: back
        in: query
        description: The number of days back to fetch observations.
        schema:
          type: integer
          default: 14
          minimum: 1
          maximum: 30
      - name: cat
        in: query
        description: Only fetch observations from these taxonomic categories.
        schema:
          type: string
          default: all
      - name: hotspot
        in: query
        description: Only fetch observations from hotspots.
        schema:
          type: boolean
          default: false
      - name: includeProvisional
        in: query
        description: Include observations which have not yet been reviewed.
        schema:
          type: boolean
          default: false
      - name: maxResults
        in: query
        description: Only fetch this number of observations.
        schema:
          type: integer
          default: all
          minimum: 1
          maximum: 10000
      - name: r
        in: query
        description: Fetch observations from up to 10 locations.
        schema:
          type: string
      - name: sppLocale
        in: query
        description: Use this language for species common names.
        schema:
          type: string
          default: en
      responses:
        '200':
          description: A list of recent observations
          content:
            application/json:
              schema:
                type: array
                items:
                  "$ref": "#/components/schemas/Observation"                        
  /data/obs/{regionCode}/recent/notable:
    get:
      operationId: getRecentNotableObservations
      summary: Recent notable observations in a region
      parameters:
      - name: regionCode
        in: path
        required: true
        description: The country, subnational1, subnational2 or location code.
        schema:
          type: string
      - name: back
        in: query
        required: false
        description: The number of days back to fetch observations.
        schema:
          type: integer
          default: 14
          minimum: 1
          maximum: 30
      - name: detail
        in: query
        required: false
        description: Include a subset (simple), or all (full), of the fields available.
        schema:
          type: string
          enum:
          - simple
          - full
          default: simple
      responses:
        '200':
          description: A list of recent notable observations
          content:
            application/json:
              schema:
                type: array
                items:
                  "$ref": "#/components/schemas/Observation"
  /data/obs/geo/recent:
    get:
      operationId: getRecentNearbyObservations
      summary: Recent nearby observations
      parameters:
      - name: lat
        in: query
        required: true
        description: Latitude to 2 decimal places.
        schema:
          type: number
          format: float
          minimum: -90
          maximum: 90
      - name: lng
        in: query
        required: true
        description: Longitude to 2 decimal places.
        schema:
          type: number
          format: float
          minimum: -180
          maximum: 180
      responses:
        '200':
          description: A list of recent nearby observations
          content:
            application/json:
              schema:
                type: array
                items:
                  "$ref": "#/components/schemas/Observation"
components:        
  schemas:
    Observation:
      type: object
      properties:
        comName:
          type: string
        sciName:
          type: string
        locId:
          type: string
        locName:
          type: string
        obsDt:
          type: string
        howMany:
          type: integer
        lat:
          type: number
        lng:
          type: number
        obsValid:
          type: boolean
        obsReviewed:
          type: boolean
        locationPrivate:
          type: boolean
        speciesCode:
          type: string
    ErrorResponse:
      type: object
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
    HistoricObservationResponse:
      type: array
      items:
        type: object
        properties:
          speciesCode:
            type: string
          comName:
            type: string
          sciName:
            type: string
          locId:
            type: string
          locName:
            type: string
          obsDt:
            type: string
            format: date-time
          howMany:
            type: integer
            format: int32
          lat:
            type: number
            format: double
          lng:
            type: number
            format: string
          obsValid:
            type: boolean
          obsReviewed:
            type: boolean
          locationPrivate:
            type: boolean
          subId:
            type: string
          subnational1Code:
            type: string
          subnational1Name:
            type: string
    ApiKeyAuth:
      type: apiKey
      in: header
      name: X-eBirdApiToken
security:
  - ApiKeyAuth: []


 
